# Generated by Django 3.2.5 on 2021-07-07 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('Prevision', models.CharField(max_length=50)),
                ('Especialidad', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=30)),
                ('Comuna', models.CharField(max_length=30)),
                ('Centro_Medico', models.CharField(max_length=30)),
                ('Fecha_de_Consulta', models.DateField(blank=True, null=True)),
                ('Creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
